[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "yarn dev" # Command to start your dev server
  targetPort = 3000 # The port for your application server, framework, or site generator